/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f93419094dc450ca0909ccf46eb4a048)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	PUBLIC_ORIGIN: "https://auth-coffee.muralooo.win";
	GOOGLE_IOS_CLIENT_ID: "260197318794-dle7fel1us34ffughest6qd2e8pna1tf.apps.googleusercontent.com";
	GOOGLE_CLIENT_ID: "260197318794-cd79hiok6b4na7fp10o2dakcu5li4fi2.apps.googleusercontent.com";
	ADMIN_GOOGLE_EMAIL: "mural86@gmail.com";
	ALLOWED_EMAILS: "mural86@gmail.com";
	SESSIONS: DurableObjectNamespace<import("./src/index").LoginAttempt>;
	ADMIN_DIRECTORY: DurableObjectNamespace<import("./src/index").AdminDirectory>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "LoginAttempt" | "AdminDirectory";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "GOOGLE_IOS_CLIENT_ID" | "GOOGLE_CLIENT_ID" | "ADMIN_GOOGLE_EMAIL" | "ALLOWED_EMAILS">> {}
}
